# We use the module we just built
FROM kvalitetsit/gooioidwsrest as caddybuilder
ENV GO111MODULE=on

# Prepare for custom caddy build
RUN mkdir /caddy
WORKDIR /caddy
RUN go mod init caddy
RUN echo "replace github.com/russellhaering/goxmldsig => github.com/evtr/goxmldsig latest" >> go.mod
#RUN echo "replace github.com/caddyserver/caddy => github.com/evtr/caddy 1917695d7e6fa7a9245669cdae1633917402bbcd" >> go.mod
RUN echo "replace oioidwsrest => ../oioidwsrest" >> go.mod

# Kitcaddy module source
COPY ./caddy-plugin /caddy/
RUN go test caddy/caddyoioidwsrest
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/bin/caddy .

#FROM abiosoft/caddy:1.0.1
FROM alpine:3.10
COPY --from=caddybuilder /go/bin/caddy /usr/bin/caddy
RUN /usr/bin/caddy version
RUN /usr/bin/caddy list-modules
ENTRYPOINT ["/usr/bin/caddy", "run"]
