# We use the module we just built
FROM kvalitetsit/gooioidwsrest as caddybuilder
ENV GO111MODULE=on

# Prepare for custom caddy build
RUN mkdir /caddy
WORKDIR /caddy
RUN go mod init caddy
RUN echo "replace github.com/russellhaering/goxmldsig => github.com/evtr/goxmldsig latest" >> go.mod
RUN echo "replace oioidwsrest => ../oioidwsrest" >> go.mod

# Kitcaddy module source
COPY ./caddy-plugin /caddy/
RUN go test caddy/caddyoioidwsrest
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/bin/caddy .

FROM scratch
COPY --from=caddybuilder /go/bin/caddy /usr/bin/caddy
ENTRYPOINT ["/usr/bin/caddy", "run"]
