FROM alpine:3.10.3
RUN apk add --update --no-cache gettext
COPY ./caddytemplates/caddyfiletemplates/Caddyfile-wsc /caddyfiletemplates/Caddyfile-wsc
ENTRYPOINT envsubst < ${TEMPLATE_FILE} > ${CADDYFILE}
