FROM kvalitetsit/gooioidwsrest-templates

ADD ./wsp/testserviceaa-ssl.crt /ssl/testserviceaa-ssl.crt
ADD ./wsp/testserviceaa-ssl.key /ssl/testserviceaa-ssl.key

ADD  ./sts/sts.cer /wsp/trust/sts.cer

ADD  ./wsp/Caddyfile-wsp /wsp/Caddyfile-wsp

VOLUME /wsp
VOLUME /ssl
