version: '2'
networks:
  gooioidwsrest:
    driver: bridge
services:
   mysql:
     image: mysql:5.5
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=sts
       - MYSQL_USER=sts
       - MYSQL_PASSWORD=sts123
     networks:
       - gooioidwsrest
   mongo:
     image: mongo:3.3
     networks:
       - gooioidwsrest
