FROM kvalitetsit/gooioidwsrest-templates

# WSC certificates
ADD ./wsc/client/medcom.cer /wsc/certificates/client.cer
ADD ./wsc/client/medcom.pem /wsc/certificates/client.pem
ADD ./sts/sts.cer /wsc/trust/sts.cer
ADD ./wsp/testserviceaa-ssl.crt /wsc/trust/testserviceaa.cer

# WSP certificates
ADD ./wsp/testserviceaa-ssl.crt /ssl/testserviceaa-ssl.crt
ADD ./wsp/testserviceaa-ssl.key /ssl/testserviceaa-ssl.key
ADD ./sts/sts.cer /wsp/trust/sts.cer

# Generate WSP config
ENV SSL_HOST_NAME testserviceaa
ENV LISTEN_PORT 443
ENV MONGO_HOST mongo
ENV MONGO_DATABASE testwsp2
ENV WSP_SSL_CERTIFICATE_FILE /ssl/testserviceaa-ssl.crt
ENV WSP_SSL_KEY_FILE /ssl/testserviceaa-ssl.key
ENV WSP_BACKEND_HOST testservicea-backend
ENV WSP_BACKEND_PORT 80
ENV WSP_AUDIENCE_RESTRICTION urn:kit:testa:servicea
ENV WSP_TRUST_CERT_FILES \"/wsp/trust/sts.cer\"
RUN envsubst < /caddyfiletemplates/Caddyfile-wsp > /tmp/caddywsp.json

# Generate WSC config pointing to caddy WSP above
ENV LISTEN_PORT 8080
ENV MONGO_HOST mongo
ENV MONGO_DATABASE testwsc8080
ENV WSC_STS_URL https://sts/sts/service/sts
ENV WSC_CLIENT_CERTIFICATE_FILE /wsc/certificates/client.cer
ENV WSC_CLIENT_KEY_FILE /wsc/certificates/client.pem
ENV WSC_SERVICE_ENDPOINT_HOST testserviceaa
ENV WSC_SERVICE_ENDPOINT_PORT 443
ENV WSC_SERVICE_AUDIENCE urn:kit:testa:servicea
ENV WSC_TRUST_CERT_FILES \"/wsc/trust/sts.cer\", \"/wsc/trust/testserviceaa.cer\"
RUN envsubst < /caddyfiletemplates/Caddyfile-wsc-nosessiondata > /tmp/caddywscnosession.json

# Generate WSC config acting as WSC for the WSP defined above
ENV LISTEN_PORT 8090
ENV MONGO_HOST mongo
ENV MONGO_DATABASE testwsc8090
ENV WSC_STS_URL https://sts/sts/service/sts
ENV WSC_CLIENT_CERTIFICATE_FILE /wsc/certificates/client.cer
ENV WSC_CLIENT_KEY_FILE /wsc/certificates/client.pem
ENV WSC_SERVICE_ENDPOINT_HOST testserviceaa
ENV WSC_SERVICE_ENDPOINT_PORT 443
ENV WSC_SERVICE_AUDIENCE urn:kit:testa:servicea
ENV WSC_SESSION_DATA_URL https://testserviceaa
ENV WSC_TRUST_CERT_FILES \"/wsc/trust/sts.cer\", \"/wsc/trust/testserviceaa.cer\"
RUN envsubst < /caddyfiletemplates/Caddyfile-wsc > /tmp/caddywscsession.json



# Merge config files
RUN mkdir /caddy
RUN jq -s '.[0] * .[1] * .[2]' /tmp/caddywsp.json /tmp/caddywscnosession.json /tmp/caddywscsession.json > /caddy/config.json
RUN cat /caddy/config.json

VOLUME /wsc
VOLUME /wsp
VOLUME /ssl
VOLUME /caddy

