version: '2'
networks:
  gooioidwsrest:
    driver: bridge
services:
   wsc-resources:
     image: build-gooioidwsrestresources/wsc
     build:
       context: .
       dockerfile: Dockerfile-resources-wsc
# Wsc
   wsc:
     image: kvalitetsit/caddy-gooioidwsrest
     environment:
       - mongo_host=mongo
     volumes_from:
       - wsc-resources:ro
#     ports:
#       - "8080:8080"
#       - "8070:8070"
     command:
      - "--log"
      - "stdout"
      - "--conf"
      - "/wsc/config/Caddyfile-wsc"
     networks:
       - gooioidwsrest

